#!/usr/bin/env python
import subprocess

def prompt():
    YES = set(['yes','y', 'ye', ''])
    NO = set(['no','n'])

    print '[y/n] >',
    choice = raw_input().lower()
    if choice in YES:
        return True
    elif choice in NO:
        return False
    else:
        return None

commands = [
    ('Add $(pwd)/bin to PATH (/etc/paths)?', 'sudo echo $(pwd)/bin >> /etc/paths'),
    ('Overwrite ~/.bash_profile?', 'cp ./.bash_profile ~'),
]

for command in commands:
    subprocess.call(['/bin/bash', '-c', 'echo " --- ' + command[0] + '"'])

    while True:
        answer = prompt()
        if answer is True:
            subprocess.call(['/bin/bash', '-c', command[1]])

        if answer is not None:
            break
